### ISSUE TITLE
Add minimum OS version supported for iOS and Android

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter_templates#37]
## Why

Every project defines the minimum OS version for the app, so it can limit the deprecated APIs and features that no longer exist. The min OS version should follow the market trend to target as much audience as possible.

As the statistic from [statcounter](https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/worldwide), there are more than 80% of devices running iOS 14 or later. So `min iOS could be 14.0`.

![image](https://user-images.githubusercontent.com/60863885/154890899-9d18e1dd-842f-4a65-8cd9-4dd63715a6af.png)

With Android, the min OS version is wider but it should not be too old. So we can go with `Android 6.0` aka `API level 23` as described in the statistic site.

![image](https://user-images.githubusercontent.com/60863885/154892270-5b2840fa-db97-48da-9e41-5144a16c4f27.png)

If you agree to this proposal, please give a thumb up 👍

## Who Benefits?

Developers

**Comment by olivierobert** [comment]
iOS 14 might be too high. Most of our clients still have much lower targets. @nimblehq/ios-chapter please provide more info on current respective iOS project to Manh.

**Comment by luongvo** [comment]
I agree to start from `Android 6.0 (API 23)`.

For iOS, I don't think we should start from iOS 14 as it's too high. Currently, our Varun project runs on `iOS 9` and may need to upgrade to `iOS 10` because of the latest version of [`firebase-core` requirement](https://pub.dev/packages/firebase_messaging/versions/10.0.1/changelog#800-dev12). If we still don't have any issue with `iOS 10`, should we start from this version? 🤔

**Comment by manh-t** [comment]
@olivierobert @luongvo the min OS version could be changed when applying to the project. I agree that `iOS 14` might be too high, but `iOS 9` or `iOS 10` are too old imo since my iPhone 6 is now running `iOS 12` at the latest. How about `iOS 12`?
I would love to hear the opinion from @nimblehq/ios-chapter as well 🙇

**Comment by suho** [comment]
We still have a project that is supporting `iOS 10`, so I would prefer to use `iOS 10`. If you are not using any specific frameworks (CoreML, ARKit, SwiftUI, Combine...) or APIs from a higher iOS version then supporting from `iOS 10` would be great.
Did you face any issues because of the OS version? (except the firebase-core requirement?)

**Comment by markgravity** [comment]
I also think the minimum iOS version should be `iOS 10`, then we can increase the minimum base on each specific project if needed.

Imagine if we choose the minimum iOS version is `iOS 14` but our client project requires us to support iOS 12 that may lead our template unable to apply, IMO 🤔

**Comment by manh-t** [comment]
I grab all your opinions and appreciate them 🙏 👏  So let's go with `min iOS version 10` for our template, it's a good start. Thank you for taking time 🙇 😁

**Comment by luongvo** [comment]
Who's working on this ticket please? 🤔

**Comment by manh-t** [comment]
@luongvo me 🙋
